name: call_detector_plugin
description: "A Flutter plugin for detecting incoming, outgoing, and active calls on Android and iOS devices"
version: 1.0.1
homepage: https://github.com/javlon92/call_detector_plugin
repository: https://github.com/javlon92/call_detector_plugin
issue_tracker: https://github.com/javlon92/call_detector_plugin/issues

topics:
  - call-detector
  - call-detecting
  - call-tracking
  - call-handler
  - phone-detector

platforms:
  android:
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9
  test: ^1.25.15
  fake_async: ^1.3.1
  mockito: ^5.4.4
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.call_detector_plugin
        pluginClass: CallDetectorPlugin
      ios:
        pluginClass: CallDetectorPlugin
